const express = require("express");
const controllers = require("../controllers/controller");
const router = express.Router();
router.post("/signup", controllers.signup);
router.post("/login", controllers.login);
// router.get("/auth", controllers.auth);
router.get("/data", controllers.auth, controllers.getData);
router.post("/addPost", controllers.auth, controllers.addPost);
router.post("/addComment", controllers.auth, controllers.addComment);
router.post("/addLike", controllers.auth, controllers.addLike);
router.post("/removeLike", controllers.auth, controllers.removeLike);
module.exports = router;
